I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 41, in script
    show image game_core.chars["Aria"]["Stressed"] at right with dissolve
  File "game/script.rpy", line 41, in <module>
    show image game_core.chars["Aria"]["Stressed"] at right with dissolve
KeyError: 'Stressed'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 41, in script
    show image game_core.chars["Aria"]["Stressed"] at right with dissolve
  File "S:\Software\renpy-8.1.1-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "S:\Software\renpy-8.1.1-sdk\renpy\ast.py", line 1384, in show_imspec
    expression = renpy.python.py_eval(expression)
  File "S:\Software\renpy-8.1.1-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "S:\Software\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 41, in <module>
    show image game_core.chars["Aria"]["Stressed"] at right with dissolve
KeyError: 'Stressed'

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.1.23060707
ChordWeaver Chronicles 1.0
Sat Nov 25 18:22:36 2023
