I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script call
    call rhythm_game_entry_label
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 28, in script
    $ rhythm_game_displayable = RhythmGameDisplayable(selected_song)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 28, in <module>
    $ rhythm_game_displayable = RhythmGameDisplayable(selected_song)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 293, in __init__
    self.track_bar_drawable = Solid('#000000', 0.5, xsize=self.track_bar_width, ysize=self.track_bar_height)
TypeError: __init__() takes 2 positional arguments but 3 were given

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script call
    call rhythm_game_entry_label
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 28, in script
    $ rhythm_game_displayable = RhythmGameDisplayable(selected_song)
  File "/Users/erikacheyenne/Desktop/Game Development/RenPy/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/erikacheyenne/Desktop/Game Development/RenPy/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 28, in <module>
    $ rhythm_game_displayable = RhythmGameDisplayable(selected_song)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 293, in __init__
    self.track_bar_drawable = Solid('#000000', 0.5, xsize=self.track_bar_width, ysize=self.track_bar_height)
TypeError: __init__() takes 2 positional arguments but 3 were given

macOS-14.0-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
ChordWeaver Chronicles 1.0
Fri Nov  3 12:57:34 2023
